---
spring:
    application:
        name: dcis-players
        admin:
            enabled: false
    profiles:
        active:
        - LOCAL
    main:
        banner-mode: off

#    mvc:
#        servlet:
#            path: /players

    security:
        user:
            name: monitor
            password: observing
            roles: OBSERVER
        oauth2:
            client:
                registration:
                    delphi-council:
                        provider: delphi-council
                        authorization-grant-type: authorization_code
                        scope: openid,profile

                provider:
                    delphi-council:
                        issuerUri: https://sso.kaiserpfalz-edv.de/realms/delphi-council
                        userNameAttribute: preferred_username
            resourceserver:
                jwt:
                    issuerUri: https://sso.kaiserpfalz-edv.de/realms/delphi-council

server:
    error:  
        whitelabel:
            enabled: false
    servlet:
        contextPath: /players

management:
    tracing:
        sampling:
            probability: 1
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info,env,prometheus
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true



## default connection pool
#spring.datasource.hikari.connectionTimeout=20000
#spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
#spring.datasource.username=mkyong
#spring.datasource.password=password

## create and drop table, good for testing, production set to none or comment it
#spring.jpa.hibernate.ddl-auto=validate

logging:
    group:
        rest: de.paladinsinn.tp.dcis.api,org.springframework.web,org.springframework.http
    level:
        web: DEBUG
        security: DEBUG
        rest: DEBUG
        org:
            springframework:
                security: DEBUG
        de:
            paladinsinn: TRACE