---
spring:
    application:
        name: dcis-players
        admin:
            enabled: true
    main:
        banner-mode: off

    datasource:
        url: ${DB_pgbouncer-jdbc-uri}
        username: ${DB_user}
        password: ${DB_password}

        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5

        jpa:
            hibernate:
                ddl-auto: validate

#    mvc:
#        servlet:
#            path: /players

    security:
        user:
            name: monitor
            password: observing
            roles: OBSERVER
        oauth2:
            client:
                registration:
                    delphi-council:
                        provider: delphi-council
                        authorizationGrantType: authorization_code
                        scope: openid,profile,roles,microprofile-jwt

                provider:
                    delphi-council:
                        issuerUri: https://sso.kaiserpfalz-edv.de/realms/delphi-council
                        userNameAttribute: preferred_username
            resourceserver:
                jwt:
                    issuerUri: https://sso.kaiserpfalz-edv.de/realms/delphi-council
                    jwkSetUri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

kp:
    security:
        keycloak:
            group-authority-mapper:
                role-attribute: groups

server:
    error:  
        whitelabel:
            enabled: false
    servlet:
        contextPath: /players

management:
    tracing:
        sampling:
            probability: 1
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info,env,prometheus
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true




logging:
    group:
        rest: de.paladinsinn.tp.dcis.api,org.springframework.web,org.springframework.http
    level:
        web: INFO
        security: INFO
        rest: INFO
        de:
            paladinsinn: TRACE
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG
