---
spring:
    profiles:
        active: LOCAL
        
    application:
        name: dcis-users-amqp
        admin:
            enabled: true
    main:
        banner-mode: off

    datasource:
        url: ${PGO_pgbouncer-jdbc-uri}
        username: ${PGO_user:postgres}
        password: ${PGO_password:postgres}
        driverClassName: org.postgresql.Driver

        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5

    jpa:
        database: POSTGRESQL
        showSql: true
        hibernate:
            ddlAuto: validate
    
    liquibase:
        enabled: true
        showSummaryOutput: console
        uiService: console

    security:
        user:
            name: monitor
            password: observing
            roles: ACTUATOR

server:
    error:
        whitelabel:
            enabled: false
    port: ${HTTP_PORT:8080}
    servlet:
        contextPath: /users

management:
    server:
        port: ${METRICS_PORT:8081}
        contextPath: /
    ssl:
        enabled: false
    tracing:
        sampling:
            probability: 1
    endpoint:
        health:
            probes:
                enabled: true
        httptrace:
            enabled: true
        liquibase:
            enabled: true
        scheduledtasks:
            enabled: true
        metrics:
            enabled: true
        configprops:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health,info,env,prometheus,httptrace,*
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true

logging:
    group:
        rest: de.paladinsinn.tp.dcis.api,org.springframework.web,org.springframework.http
    level:
        web: TRACE
        security: TRACE
        rest: TRACE
        liquibase: INFO
        de:
            paladinsinn: TRACE
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: TRACE
