---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: dcis-users-dev
  namespace: argocd
spec:
  project: torganized-play
  sources:
  - repoURL: quay.io/Kaiserpfalzedv/helm
    chart: microservice
    targetRevision: 2.1.3
    helm:
      valueFiles:
      - $values/torganized-play-dev/dcis-users.yaml
  - repoURL: https://github.com/KaiserpfalzEDV/cluster-gitops.git
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: torganized-play-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s