---
name: Build Java Libraries

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main','develop']
    paths:
    - 'api/**'
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java for publishing to GitHub Packages
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build and Publish to GitHub Packages
      run: for dir in api persistence ; do cd $dir ; mvn --batch-mode --no-transfer-progress deploy ; cd .. ; done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
