---
name: Build Libraries

on:
  release:
    types: [created]
  push:
    branches: ['develop']
    paths:
    - 'api/**'
    - 'commons/**'
  workflow_dispatch:

jobs:
  publish-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Publish API
      run: cd api && mvn --batch-mode --no-transfer-progress deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish-commons:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Publish commons
      run: cd commons && mvn --batch-mode --no-transfer-progress deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

